{% set name = "napari-accelerated-pixel-and-object-classification" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-accelerated-pixel-and-object-classification-{{ version }}.tar.gz
  sha256: 2f626a9c2d671bf32cade62df74666eef328e6dc3f6d7f3ab6091a992131fb5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - apoc-backend >=0.12.0
    - magicgui
    - napari >=0.4.11
    - napari-plugin-engine >=0.1.4
    - napari-time-slicer
    - napari-tools-menu >=0.1.17
    - numpy
    - pandas
    - pyopencl
    - python >={{ python_min }}
    - qtpy
    - superqt
    - napari-assistant >=0.4.7
    - jupytext
    - jupyter

test:
  imports:
    - napari_accelerated_pixel_and_object_classification
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-accelerated-pixel-and-object-classification
  summary: Pixel and label classification using OpenCL-based Random Forest Classifiers
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/haesleinhuepf/napari-accelerated-pixel-and-object-classification

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - haesleinhuepf
